#!/bin/bash

file="./diceware8k.txt"
words=6

for (( i=1; i<=$words; i++ )); do

	printf "$( sort -R --random-source=/dev/urandom $file | head -n1 )"
	
	if [[ $i == $words ]]; then
		printf "\n"
	else
		printf " "
	fi
	
done
